import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { ArrowRight, Search, TrendingUp, X, Activity, AlertCircle, ChevronDown, Eye, ArrowLeft } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { Link, useNavigate } from "react-router-dom";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DashboardLayout } from "@/components/DashboardLayout";
import { toast } from "@/components/ui/use-toast";
import { fetchMediaAlerts } from "@/lib/media-agent-data";
import { ArticlePreviewModal } from "@/components/media/ArticlePreviewModal";

const severityColor = (severity: string) =>
  severity === "critical"
    ? "bg-destructive/10 text-destructive border-destructive/20"
    : severity === "high"
      ? "bg-warning/10 text-warning border-warning/20"
      : "bg-primary/10 text-primary border-primary/20";

export default function MediaAlerts() {
  const { data: alerts = [] } = useQuery({ queryKey: ["media-live-alerts"], queryFn: () => fetchMediaAlerts(12), refetchInterval: 10000 });
  const [previewAlert, setPreviewAlert] = useState<any | null>(null);
  const navigate = useNavigate();

  return (
    <DashboardLayout>
      <div className="space-y-6 p-6">
        <motion.div initial={{ opacity: 0, y: 12 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.4 }} className="flex flex-col sm:flex-row sm:items-end justify-between gap-4 pb-2">
          <div>
            <Link to="/media" className="inline-flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-muted-foreground hover:text-indigo-600 mb-4 transition-colors">
              <ArrowLeft className="h-4 w-4" /> Back to Media Agent
            </Link>
            <div className="flex items-center gap-3 mb-2">
              <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-red-500 to-rose-600 flex items-center justify-center shadow-lg shadow-red-500/20">
                <Activity className="h-5 w-5 text-white animate-pulse" />
              </div>
              <div>
                <h1 className="text-3xl font-bold tracking-tight bg-clip-text text-transparent bg-gradient-to-r from-foreground to-foreground/70">Live Alerts Feed</h1>
                <p className="text-sm text-muted-foreground mt-0.5">Real-time intelligence generated by the autonomous adverse media pipeline</p>
              </div>
            </div>
          </div>
          <Badge className="bg-destructive/10 text-destructive border-destructive/20 animate-pulse gap-1.5 py-1 px-3 shadow-sm mb-2 sm:mb-0">
            <AlertCircle className="h-3.5 w-3.5" />
            <span className="font-bold tracking-wider">LIVE STREAM</span>
          </Badge>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.5, delay: 0.1 }}>
          <div className="rounded-2xl border border-border/50 bg-card/60 backdrop-blur-sm p-5 shadow-sm">
            <div className="flex flex-wrap items-center justify-center gap-3">
              {["Article Detected", "Entity Extraction", "Portfolio Match", "Risk Scoring", "Alert Created"].map((step, index) => (
                <div key={step} className="flex items-center gap-3">
                  <div className={`rounded-xl border px-4 py-2 text-xs font-bold uppercase tracking-wider transition-all hover:scale-105 ${index === 4 ? "border-destructive/30 bg-destructive text-destructive-foreground shadow-md shadow-destructive/20" : "border-border/50 bg-white shadow-sm text-muted-foreground hover:text-foreground"}`}>
                    {step}
                  </div>
                  {index < 4 && <ArrowRight className="h-4 w-4 text-muted-foreground/30" />}
                </div>
              ))}
            </div>
          </div>
        </motion.div>

        <div className="space-y-4">
          {alerts.map((alert, index) => {
            return (
              <motion.div key={alert.id} initial={{ opacity: 0, x: -20 }} animate={{ opacity: 1, x: 0 }} transition={{ duration: 0.4, delay: 0.1 + index * 0.08 }}>
                <div 
                  onClick={() => navigate(`/investigations/${alert.id}`, { state: { entity: { name: alert.entityName, risk_score: alert.severity === "critical" ? 95 : 75, latest_signal: alert.title } } })}
                  className={`group cursor-pointer relative overflow-hidden rounded-2xl border bg-gradient-to-b from-card to-card/50 p-6 shadow-sm transition-all hover:-translate-y-1 hover:shadow-lg hover:border-border border-l-4 ${alert.severity === "critical" ? "border-l-destructive hover:border-l-destructive" : alert.severity === "high" ? "border-l-warning hover:border-l-warning" : "border-l-primary hover:border-l-primary"}`}
                >
                  <div className="absolute inset-0 bg-gradient-to-br from-indigo-500/5 via-transparent to-transparent opacity-0 transition-opacity group-hover:opacity-100 pointer-events-none" />
                  <div className="absolute -top-4 -right-4 p-4 opacity-[0.03] pointer-events-none group-hover:scale-110 group-hover:opacity-[0.05] transition-all duration-500">
                    <Activity className="h-32 w-32" />
                  </div>
                  
                  <div className="relative z-10 flex items-start justify-between gap-4">
                    <div className="flex-1">
                      <div className="mb-3 flex items-center gap-3">
                        <Badge className={`px-2 py-0.5 text-[10px] font-bold tracking-wider uppercase ${severityColor(alert.severity)}`}>{alert.severity}</Badge>
                        <span className="text-[10px] font-mono text-muted-foreground font-bold">{new Date(alert.generatedAt).toLocaleString()}</span>
                      </div>
                      <h3 className="mb-1.5 text-lg font-bold tracking-tight text-foreground group-hover:text-indigo-600 transition-colors">{alert.title}</h3>
                      <p className={`text-sm text-muted-foreground leading-relaxed max-w-4xl transition-all line-clamp-2`}>
                        {alert.summary}
                      </p>
                    </div>
                    
                    <div className="mt-2 shrink-0 flex items-center gap-2">
                      <Button
                        size="icon"
                        variant="ghost"
                        onClick={(e) => {
                          e.stopPropagation();
                          setPreviewAlert(alert);
                        }}
                        className="h-9 w-9 rounded-full bg-indigo-50 text-indigo-600 hover:bg-indigo-100 hover:text-indigo-700 shadow-sm transition-colors"
                        title="Preview Article"
                      >
                        <Eye className="h-4 w-4" />
                      </Button>
                      <Button
                        size="sm"
                        onClick={(e) => {
                          e.stopPropagation();
                          navigate(`/investigations/${alert.id}`, { state: { entity: { name: alert.entityName, risk_score: alert.severity === "critical" ? 95 : 75, latest_signal: alert.title } } });
                        }}
                        className="h-9 px-3 gap-2 text-xs font-bold rounded-xl bg-indigo-600 text-white hover:bg-indigo-700 shadow-sm transition-colors"
                      >
                        <Search className="h-4 w-4" />
                        Investigate
                      </Button>
                    </div>
                  </div>
                </div>
              </motion.div>
            );
          })}
        </div>
      </div>
      
      {/* Article Preview Modal */}
      <ArticlePreviewModal 
        open={!!previewAlert} 
        onOpenChange={(open) => !open && setPreviewAlert(null)} 
        alert={previewAlert} 
      />
    </DashboardLayout>
  );
}
